config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews
  end

  resources :users do
    resources :reviews
  end

   root 'restaurants#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :reviews, dependent: :destroy
	has_many :users, through: :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :restaurant

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :reviews

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

	def index
		@restaurants = Restaurant.all.includes(:reviews)
	end

	def new
		@restaurants = Restaurant.new
	end

	def create
		@restaurant = Restaurant.new(params.require(:restaurant).permit(:name, :address, :phone))
		@restaurant.save
		redirect_to restaurants_url
	end

	def show
		@restaurant = Restaurant.find(params[:id])
		@review = Review.new
		@users = User.all
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def create
		@restaurant = Restaurant.find(params[:restaurant_id])
		@review = @restaurant.reviews.create(params_including_user_id)
		flash[:notice] = "Woohoo new review!"
		redirect_to @restaurant
	end	

	 def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@restaurant)
  end

  def params_including_user_id
  	review_params.merge(user_id: session[:user_id])
  end

	private
		def review_params
			params.require(:review).permit(:comment, :rating, :recommend)
		end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		# my params has is 
		params[:email]
		user = User.where(email: params[:email]).first
		
		if user
			session[:user_id] = user.id
			flash[:notice] = "Welcome back, #{user.name}!"
			redirect_to root_url
		else
			flash[:alert] = "You type like a dumbass"
			redirect_to login_url
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url, notice: "Get the fuck out!"
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.create(user_params)
		session[:user_id] = @user.id
		redirect_to root_url, notice: "You have entered into my world"	
	end


	private
	def user_params
		params.require(:user).permit(:email, :name)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestaurantReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% if session[:user_id] %>
		<%= form_tag '/logout', method: :delete do %>
			<%= submit_tag "Logout" %>
		<% end %>
	<% else %>
		<p><%= link_to 'Signup', signup_path %> or <%= link_to 'Log in', login_path %></p>	
	<% end %>

	<% if flash[:notice] %>
		<p id="notice"><%= flash[:notice] %></p>
	<% elsif flash[:alert] %>
		<p id="alert"><%= flash[:alert] %></p>
	<% end %>

	<%= yield %>

	<br>
	<br>
	<br>
	<br>

	<p>
	Copyright <%= "\xC2\xA9".force_encoding('UTF-8') %> <%= Date.today.year %> TIY Hopkins
	</p>


</body>
</html>

app/views/restaurants/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestaurantReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/index.html.erb
<h1>Guide to the Best Restaurants in Orlando</h1>

<p>Here are places I've eaten in the greater Orlando area, and enjoyed and/or gotten food poisoning from.</p>

<table>
	<tr>
		<th>Name</th>
		<th>Address</th>
		<th># of Reviews</th>
	</tr>
	<% @restaurants.each do |restaurant| %>
		<tr>
			<td><%= link_to restaurant.name, restaurant %></td>
			<td><%= restaurant.address %></td>
			<td><%= restaurant.reviews.length %></td>
		</tr>	
	<% end %>
</table>
<br>
<br>
<%= link_to 'Add a new restaurant', new_restaurant_path  %>

app/views/restaurants/new.html.erb
<h1>Add a Restaurant</h1>

	<%= form_for @restaurants do |f| %>
		
		<fieldset>	
			<legend>Add a Restaurant</legend>
				<%= f.label :name %>
				<%= f.text_field :name %> </br>


				<%= f.label :address %>
				<%= f.text_area :address %> </br>

				<%= f.label :phone, 'Phone number' %>
				<%= f.telephone_field :phone, placeholder: "(555) 555-5555" %> </br>
				<%= f.submit 'Submit' %>
		</fieldset>		
		
	<% end %>
	<br>
	<%= link_to 'Back', root_path %>
	

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
Address: <%= @restaurant.address %><br>
Phone: <%= @restaurant.phone %>

<br>
<br>
<br>

<section>
	<h2>Reviews</h2>
		<%= render @restaurant.reviews.order(created_at: :desc) %>
</section>

<br>

<section>
	<% if session[:user_id] %>
		<%= render 'reviews/form' %>
	<% else %>
		<p><%= link_to 'Log in here', login_path %> to leave a review </p>
	<% end %>
</section>

<br>

<%= link_to 'Back', root_path %>

app/views/reviews/_form.html.erb
<%= form_for [ @restaurant, @review ] do |f| %>
	<fieldset>
		<legend>Add a Review</legend>

		<p>
			<%= f.label :comment %><br>
			<%= f.text_area :comment, rows: 10, cols: 35 %>
		</p>
		<p>
			<%= f.label :rating %>
			<%= f.select :rating, options_for_select([["1 (lowest)", 1], 2,3,4,5]) %>
		<p>
			<%= f.label :recommend, "Would You Recommend?" %>
			<%= f.check_box :recommend %>
		</p>

		</p>
			<%= f.submit %>
		</p>

	</fieldset>
		
<% end %>

app/views/reviews/_review.html.erb
<article>
	<p <%= 'class=recommended' if review.recommend? %>>
		<strong>Rating:</strong>
		<%= review.rating %>
	</p>
	
	<% if review.recommend? %>
	<p>
		RECOMMENDED!
	</p>
	<% end %>

	<p>
		<strong>Comment:</strong>
		<%= review.comment %>
	</p>

	<p>
		<strong>Post by:</strong>
		<%= review.user.name %> at <%= time_ago_in_words review.created_at %> ago
	</p>

	<p>
	  <%= link_to 'Delete', [review.restaurant, review],
	               method: :delete,
	               data: { confirm: 'Are you sure?' } %>
	</p>
</article>

app/views/reviews/form.html.erb
<%= form_for [ @restaurant, @review ] do |f| %>
	<p>
		<%= f.label :user_id, "User name" %>
		<%= f.select :user_id, @users.collect{|user| [user.name, user.id]} %>
	</p>
	<p>
		<%= f.label :comment %><br>
		<%= f.text_area :comment %>
	</p>
	<p>
		<%= f.label :rating %>
		<%= f.select :rating, options_for_select([["1 (lowest)", 1], 2,3,4,5]) %>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up Or Else</h1>

<%= form_for @user do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :email %>
	<%= f.text_field :email %>

	<%= f.submit 'Welcome to the site' %>
<% end %>